import { ArrowRight, Check, PhoneCall, MessageSquareText, ShieldCheck, Clock3, Users } from "lucide-react";
import { Nav } from "@/components/nav";
import { Demo } from "@/components/demo";
import { Calculator } from "@/components/calculator";
import { PilotForm } from "@/components/pilot-form";
import { FAQ } from "@/components/faq";
import { TrackedLink } from "@/components/tracked-link";
import { CookieSettings } from "@/components/cookie-banner";
import { siteUrl } from "@/lib/site";
import { hasMerchantIdentity, merchantIdentity } from "@/lib/legal";

const included = ["Automatisk uppföljning av missade samtal","Anpassat SMS med företagets namn","Kunden kan svara direkt","Leadinkorg och tydlig status","Grundläggande statistik","Guidad självanslutning"];
const faq: [string,string][] = [
  ["Behöver vi byta telefonnummer?","Nej, kunderna fortsätter ringa företagets vanliga nummer. Vid ej svar vidarekopplas samtalet till ett separat Textback-nummer."],
  ["Kan vi ansluta flera telefonnummer?","Självbetjäningen gäller ett telefonnummer per abonnemang. Kontakta oss för flera nummer eller en särskild telefonilösning."],
  ["Hur snabbt skickas SMS:et?","Meddelandet skapas kort efter att det vidarekopplade samtalet har registrerats som missat. Exakt tid kan påverkas av operatören."],
  ["Kan kunden svara?","Ja. Kundens svar samlas i Textback så att företaget kan följa upp förfrågan."],
  ["Fungerar det med alla operatörer?","Inte nödvändigtvis. Därför genomför ni ett guidat vidarekopplings- och SMS-test innan tjänsten aktiveras och debiteringen börjar."],
  ["Finns det bindningstid?","Nej. Textback löper månadsvis och kan avslutas när som helst inför nästa betalningsperiod."],
  ["När betalar vi?","Stripe sparar betalmetoden säkert under anslutningen. Ingen debitering sker förrän telefonin har klarat testerna och Textback aktiveras."],
];
const jsonLd={"@context":"https://schema.org","@graph":[{"@type":"SoftwareApplication",name:"Textback",applicationCategory:"BusinessApplication",operatingSystem:"Web",url:siteUrl,description:"Textback skickar automatiskt SMS när företag missar inkommande samtal och samlar kundens svar för uppföljning.",offers:{"@type":"Offer",price:"495",priceCurrency:"SEK",description:"Lanseringspris per månad under de första tre månaderna, exklusive moms."}},{"@type":"FAQPage",mainEntity:faq.map(([question,answer])=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))}]};

export default function Home(){return <><Nav/><main id="main"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
<section id="top" className="hero"><div className="shell hero-grid"><div><span className="eyebrow">Automatiskt SMS vid missat samtal</span><h1>Missa samtalet –<br/><em>inte kunden.</em></h1><p className="lead">Textback skickar automatiskt ett SMS när företaget inte kan svara, så kunden kan beskriva sitt ärende direkt innan den kontaktar någon annan.</p><div className="cta-row"><TrackedLink href="#demo" event="hero_primary_cta_clicked" className="button large">Se hur det fungerar <ArrowRight/></TrackedLink><TrackedLink href="#ansok" event="hero_secondary_cta_clicked" className="button secondary large">Starta anslutningen</TrackedLink></div><ul className="trust"><li><Check/>495 kr/mån i tre månader</li><li><Check/>Ingen bindningstid</li><li><Check/>Ingen debitering före godkänt test</li></ul></div><HeroPhone/></div></section>
<Demo/><UseCases/><Calculator/><How/>
<section className="section bg-paper"><div className="shell"><div className="section-head"><span className="eyebrow">Det här får ni</span><h2>Från missat samtal till en förfrågan ni kan följa upp.</h2><p>Textback gör det enklare att ta hand om kunder som annars riskerar att försvinna vidare.</p></div><div className="list-card"><ul>{included.map(x=><li key={x}><Check/>{x}</li>)}</ul></div></div></section>
<Pricing/>
<section id="ansok" className="section bg-navy text-white"><div className="shell form-layout"><div><span className="eyebrow">Kom igång</span><h2>Anslut Textback utan säljmöte.</h2><p>Registrera företaget och en betalmetod hos Stripe. Därefter får ni automatiskt ett Textback-nummer, skapar portalkontot och följer en guidad anslutning.</p><div className="aside-note"><ShieldCheck/><p><b>Trygg start.</b><br/>Ingen debitering innan vidarekoppling, nummerpresentation, SMS och portal har verifierats.</p></div></div><PilotForm/></div></section>
<section id="faq" className="section"><div className="shell narrow"><div className="section-head"><span className="eyebrow">Vanliga frågor</span><h2>Det praktiska, utan finstilt säljsnack.</h2></div><FAQ items={faq}/></div></section>
<section className="final-cta"><div className="shell"><h2>Sluta låta missade samtal bli förlorade kunder.</h2><p>Starta anslutningen själv. Abonnemanget börjar först när telefonin har klarat testerna.</p><div className="cta-row center"><TrackedLink href="#ansok" event="final_cta_clicked" className="button large">Starta anslutningen</TrackedLink></div></div></section>
</main><Footer/></>}
function HeroPhone(){return <div className="hero-visual"><div className="ring ring-one"/><div className="ring ring-two"/><div className="phone hero-phone"><div className="phone-top">Meddelanden · nu</div><div className="avatar">TB</div><b>Ditt företag</b><div className="bubble outgoing">Hej! Du ringde precis till oss. Vad behöver du hjälp med?</div><div className="bubble incoming">Hej! Jag vill gärna få en offert och bli kontaktad i eftermiddag.</div><div className="mini-lead"><span className="live-dot"/> Ny kundförfrågan</div></div></div>}
function UseCases(){const cases=[[Users,"När ni hjälper en annan kund","Telefonen ringer medan personalen redan är upptagen. Kunden får direkt en väg vidare i stället för att ringa nästa företag."],[Clock3,"När ni inte kan svara direkt","Vid möten, arbete ute hos kund eller hög belastning fångar Textback upp förfrågan medan intresset fortfarande är varmt."],[PhoneCall,"När samtalet kommer efter öppettid","Kunden kan beskriva sitt ärende direkt och ni har en konkret förfrågan att följa upp nästa arbetsdag."]];return <section className="section"><div className="shell"><div className="section-head"><span className="eyebrow">När Textback gör skillnad</span><h2>Ni behöver inte vara tillgängliga varje sekund för att behålla kunden.</h2><p>Ett missat samtal behöver inte bli slutet på kundkontakten.</p></div><div className="three-grid">{cases.map(([Icon,title,text]:any)=><article className="step-card" key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>}
function How(){return <section id="sa-fungerar" className="section"><div className="shell"><div className="section-head"><span className="eyebrow">Så fungerar det</span><h2>Företagets vanliga nummer. Ett smartare nästa steg.</h2></div><div className="three-grid">{[[PhoneCall,"1","Kunden ringer","Kunden ringer företagets vanliga telefonnummer."],[PhoneCall,"2","Samtalet missas","När ingen kan svara registrerar Textback det missade samtalet."],[MessageSquareText,"3","Kunden får ett SMS","Kunden kan beskriva sitt ärende och svaret blir en förfrågan att följa upp."]].map(([Icon,n,t,p]:any)=><article className="step-card" key={n}><Icon/><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div><blockquote>Exakt anslutning beror på operatör och telefonilösning. Självbetjäningen verifierar flödet innan tjänsten aktiveras och debiteringen börjar.</blockquote></div></section>}
function Pricing(){return <section id="pris" className="section"><div className="shell pricing-layout"><div><span className="eyebrow">Lanseringserbjudande</span><h2>495 kr i månaden under de första tre månaderna.</h2><p>Därefter 995 kr/mån. Ingen bindningstid. Alla priser är exklusive moms.</p></div><article className="price-card"><span className="pill mint">Lanseringspris</span><div className="price"><strong>495 kr</strong><span>/månad i 3 månader</span></div><p>Därefter 995 kr/mån. Textback löper månadsvis och kan avslutas när som helst.</p><ul>{["Automatiska SMS efter missade samtal","Leadinkorg och kundsvar","Guidad anslutning","Ingen bindningstid"].map(x=><li key={x}><Check/>{x}</li>)}</ul><a className="button large w-full" href="#ansok">Starta anslutningen</a><p className="fine">Betalmetoden sparas hos Stripe. Debitering sker först efter godkända anslutningstester.</p></article></div></section>}
function Footer(){const configured=hasMerchantIdentity();return <footer><div className="shell footer-grid"><div><img src="/textback-logo.svg" width="180" height="45" alt="Textback"/><p>Automatisk uppföljning av missade kundsamtal.</p></div><div><b>Lösningar</b><a href="/automatiskt-sms-vid-missat-samtal">Automatiskt SMS vid missat samtal</a><a href="/missade-samtal-hantverkare">För hantverkare</a><a href="/missade-samtal-bilverkstad">För bilverkstäder</a><a href="/missade-samtal-stad-och-flyttfirma">För städ- och flyttföretag</a></div><div><b>Information</b><a href="/press">Press och logotyp</a><a href="/integritet">Integritetspolicy</a><a href="/villkor">Användarvillkor</a><a href="/pilotvillkor">Tjänstevillkor</a><a href="/cookies">Cookies</a><CookieSettings/></div><div><b>Företagsuppgifter</b>{configured?<><span>{merchantIdentity.name}</span><span>Org.nr {merchantIdentity.organizationNumber}</span><span>{merchantIdentity.address}</span></>:<span>Självbetjäningen öppnar när fullständiga säljaruppgifter har publicerats.</span>}<a href="mailto:info@textback.se">info@textback.se</a></div></div><div className="shell footer-bottom">© Textback <span>{configured?merchantIdentity.name:"Försäljning ej öppnad"}</span></div></footer>}
