import { ArrowRight, Check, PhoneCall, MessageSquareText, ShieldCheck, Clock3, Users } from "lucide-react";
import { Nav } from "@/components/nav";
import { Demo } from "@/components/demo";
import { Calculator } from "@/components/calculator";
import { PilotForm } from "@/components/pilot-form";
import { FAQ } from "@/components/faq";
import { TrackedLink } from "@/components/tracked-link";
import { CookieSettings } from "@/components/cookie-banner";
import { siteUrl } from "@/lib/site";
import { isCommerceEnabled } from "@/lib/launch-mode";
import { hasMerchantIdentity, merchantIdentity } from "@/lib/legal";

const included = ["Automatisk uppföljning av missade samtal","Anpassat SMS med företagets namn","Kunden kan svara direkt","Leadinkorg och tydlig status","Grundläggande statistik","Guidad självanslutning"];

export default function Home() {
  const commerceEnabled = isCommerceEnabled() && hasMerchantIdentity();
  const faq: [string,string][] = [
    ["Behöver vi byta telefonnummer?","Nej, kunderna fortsätter ringa företagets vanliga nummer. Vid ej svar vidarekopplas samtalet till ett separat Textback-nummer."],
    ["Kan vi ansluta flera telefonnummer?",commerceEnabled ? "Självbetjäningen gäller ett telefonnummer per abonnemang. Kontakta oss för flera nummer eller en särskild telefonilösning." : "Ja. Ange hur många nummer ni skulle vilja ansluta i intresseanmälan."],
    ["Hur snabbt skickas SMS:et?","Meddelandet skapas kort efter att det vidarekopplade samtalet har registrerats som missat. Exakt tid kan påverkas av operatören."],
    ["Kan kunden svara?","Ja. Kundens svar samlas i Textback så att företaget kan följa upp förfrågan."],
    ["Fungerar det med alla operatörer?","Inte nödvändigtvis. Därför har Textback ett guidat vidarekopplings- och SMS-test innan tjänsten aktiveras."],
    ["Finns det bindningstid?","Det planerade abonnemanget löper månadsvis utan bindningstid."],
    ["När betalar vi?",commerceEnabled ? "Stripe sparar betalmetoden säkert under anslutningen. Ingen debitering sker förrän telefonin har klarat testerna och Textback aktiveras." : "Inte i valideringsfasen. Intresseanmälan är kostnadsfri och innebär ingen beställning eller betalning."],
  ];

  const application: Record<string, unknown> = {
    "@type":"SoftwareApplication",
    name:"Textback",
    applicationCategory:"BusinessApplication",
    operatingSystem:"Web",
    url:siteUrl,
    description:"Textback skickar automatiskt SMS när företag missar inkommande samtal och samlar kundens svar för uppföljning.",
  };
  if (commerceEnabled) application.offers = {"@type":"Offer",price:"495",priceCurrency:"SEK",description:"Lanseringspris per månad under de första tre månaderna, exklusive moms."};
  const jsonLd={"@context":"https://schema.org","@graph":[application,{"@type":"FAQPage",mainEntity:faq.map(([question,answer])=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))}]};

  return <><Nav/><main id="main"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
    <section id="top" className="hero"><div className="shell hero-grid"><div><span className="eyebrow">Automatiskt SMS vid missat samtal</span><h1>Missa samtalet –<br/><em>inte kunden.</em></h1><p className="lead">Textback skickar automatiskt ett SMS när företaget inte kan svara, så kunden kan beskriva sitt ärende direkt innan den kontaktar någon annan.</p><div className="cta-row"><TrackedLink href="#demo" event="hero_primary_cta_clicked" className="button large">Se hur det fungerar <ArrowRight/></TrackedLink><TrackedLink href="#ansok" event="hero_secondary_cta_clicked" className="button secondary large">{commerceEnabled?"Starta anslutningen":"Anmäl intresse"}</TrackedLink></div><ul className="trust"><li><Check/>{commerceEnabled?"495 kr/mån i tre månader":"Kostnadsfri intresseanmälan"}</li><li><Check/>Planerad utan bindningstid</li><li><Check/>{commerceEnabled?"Ingen debitering före godkänt test":"Ingen beställning eller betalning"}</li></ul></div><HeroPhone/></div></section>
    <Demo/><UseCases/><Calculator/><How commerceEnabled={commerceEnabled}/>
    <section className="section bg-paper"><div className="shell"><div className="section-head"><span className="eyebrow">Det här får ni</span><h2>Från missat samtal till en förfrågan ni kan följa upp.</h2><p>Textback gör det enklare att ta hand om kunder som annars riskerar att försvinna vidare.</p></div><div className="list-card"><ul>{included.map(x=><li key={x}><Check/>{x}</li>)}</ul></div></div></section>
    <Pricing commerceEnabled={commerceEnabled}/>
    <section id="ansok" className="section bg-navy text-white"><div className="shell form-layout"><div><span className="eyebrow">{commerceEnabled?"Kom igång":"Produktvalidering"}</span><h2>{commerceEnabled?"Anslut Textback utan säljmöte.":"Skulle Textback lösa ett verkligt problem för er?"}</h2><p>{commerceEnabled?"Registrera företaget och en betalmetod hos Stripe. Därefter får ni automatiskt ett Textback-nummer, skapar portalkontot och följer en guidad anslutning.":"Lämna en intresseanmälan. Den används för att mäta efterfrågan och avgöra om Textback ska öppnas för pilotkunder."}</p><div className="aside-note"><ShieldCheck/><p><b>{commerceEnabled?"Trygg start.":"Ingen försäljning ännu."}</b><br/>{commerceEnabled?"Ingen debitering innan vidarekoppling, nummerpresentation, SMS och portal har verifierats.":"Formuläret innebär ingen beställning, inget avtal och ingen betalning."}</p></div></div><PilotForm commerceEnabled={commerceEnabled}/></div></section>
    <section id="faq" className="section"><div className="shell narrow"><div className="section-head"><span className="eyebrow">Vanliga frågor</span><h2>Det praktiska, utan finstilt säljsnack.</h2></div><FAQ items={faq}/></div></section>
    <section className="final-cta"><div className="shell"><h2>Sluta låta missade samtal bli förlorade kunder.</h2><p>{commerceEnabled?"Starta anslutningen själv. Abonnemanget börjar först när telefonin har klarat testerna.":"Visa att behovet finns genom att anmäla intresse för en pilotplats."}</p><div className="cta-row center"><TrackedLink href="#ansok" event="final_cta_clicked" className="button large">{commerceEnabled?"Starta anslutningen":"Anmäl intresse"}</TrackedLink></div></div></section>
  </main><Footer commerceEnabled={commerceEnabled}/></>;
}

function HeroPhone(){return <div className="hero-visual"><div className="ring ring-one"/><div className="ring ring-two"/><div className="phone hero-phone"><div className="phone-top">Meddelanden · nu</div><div className="avatar">TB</div><b>Ditt företag</b><div className="bubble outgoing">Hej! Du ringde precis till oss. Vad behöver du hjälp med?</div><div className="bubble incoming">Hej! Jag vill gärna få en offert och bli kontaktad i eftermiddag.</div><div className="mini-lead"><span className="live-dot"/> Ny kundförfrågan</div></div></div>}
function UseCases(){const cases=[[Users,"När ni hjälper en annan kund","Telefonen ringer medan personalen redan är upptagen. Kunden får direkt en väg vidare i stället för att ringa nästa företag."],[Clock3,"När ni inte kan svara direkt","Vid möten, arbete ute hos kund eller hög belastning fångar Textback upp förfrågan medan intresset fortfarande är varmt."],[PhoneCall,"När samtalet kommer efter öppettid","Kunden kan beskriva sitt ärende direkt och ni har en konkret förfrågan att följa upp nästa arbetsdag."]];return <section className="section"><div className="shell"><div className="section-head"><span className="eyebrow">När Textback gör skillnad</span><h2>Ni behöver inte vara tillgängliga varje sekund för att behålla kunden.</h2><p>Ett missat samtal behöver inte bli slutet på kundkontakten.</p></div><div className="three-grid">{cases.map(([Icon,title,text]:any)=><article className="step-card" key={title}><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>}
function How({commerceEnabled}:{commerceEnabled:boolean}){return <section id="sa-fungerar" className="section"><div className="shell"><div className="section-head"><span className="eyebrow">Så fungerar det</span><h2>Företagets vanliga nummer. Ett smartare nästa steg.</h2></div><div className="three-grid">{[[PhoneCall,"1","Kunden ringer","Kunden ringer företagets vanliga telefonnummer."],[PhoneCall,"2","Samtalet missas","När ingen kan svara registrerar Textback det missade samtalet."],[MessageSquareText,"3","Kunden får ett SMS","Kunden kan beskriva sitt ärende och svaret blir en förfrågan att följa upp."]].map(([Icon,n,t,p]:any)=><article className="step-card" key={n}><Icon/><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div><blockquote>{commerceEnabled?"Exakt anslutning beror på operatör och telefonilösning. Självbetjäningen verifierar flödet innan tjänsten aktiveras och debiteringen börjar.":"Textback är tekniskt verifierat men säljs ännu inte publikt. Intresseanmälningarna avgör om pilotlanseringen öppnas."}</blockquote></div></section>}
function Pricing({commerceEnabled}:{commerceEnabled:boolean}){return <section id="pris" className="section"><div className="shell pricing-layout"><div><span className="eyebrow">{commerceEnabled?"Lanseringserbjudande":"Planerat lanseringserbjudande"}</span><h2>495 kr i månaden under de första tre månaderna.</h2><p>Därefter planerat 995 kr/mån. Ingen bindningstid. Alla priser är exklusive moms.</p></div><article className="price-card"><span className="pill mint">{commerceEnabled?"Lanseringspris":"Planerat pris"}</span><div className="price"><strong>495 kr</strong><span>/månad i 3 månader</span></div><p>{commerceEnabled?"Därefter 995 kr/mån. Textback löper månadsvis och kan avslutas när som helst.":"Priset används för att validera betalningsviljan. Ingen tjänst beställs och ingen betalning tas emot nu."}</p><ul>{["Automatiska SMS efter missade samtal","Leadinkorg och kundsvar","Guidad anslutning","Ingen bindningstid"].map(x=><li key={x}><Check/>{x}</li>)}</ul><a className="button large w-full" href="#ansok">{commerceEnabled?"Starta anslutningen":"Anmäl intresse"}</a><p className="fine">{commerceEnabled?"Betalmetoden sparas hos Stripe. Debitering sker först efter godkända anslutningstester.":"Kostnadsfri validering. Ingen betalmetod eller debitering."}</p></article></div></section>}
function Footer({commerceEnabled}:{commerceEnabled:boolean}){return <footer><div className="shell footer-grid"><div><img src="/textback-logo.svg" width="180" height="45" alt="Textback"/><p>Automatisk uppföljning av missade kundsamtal.</p></div><div><b>Lösningar</b><a href="/automatiskt-sms-vid-missat-samtal">Automatiskt SMS vid missat samtal</a><a href="/missade-samtal-hantverkare">För hantverkare</a><a href="/missade-samtal-bilverkstad">För bilverkstäder</a><a href="/missade-samtal-stad-och-flyttfirma">För städ- och flyttföretag</a></div><div><b>Information</b><a href="/press">Press och logotyp</a><a href="/integritet">Integritetspolicy</a><a href="/villkor">Användarvillkor</a><a href="/pilotvillkor">Tjänstevillkor</a><a href="/cookies">Cookies</a><CookieSettings/></div><div><b>{commerceEnabled?"Företagsuppgifter":"Status"}</b>{commerceEnabled?<><span>{merchantIdentity.name}</span><span>Org.nr {merchantIdentity.organizationNumber}</span><span>{merchantIdentity.address}</span></>:<><span>Textback valideras inför en möjlig pilotlansering.</span><span>Försäljning och betalning är inte öppnad.</span></>}<a href="mailto:info@textback.se">info@textback.se</a></div></div><div className="shell footer-bottom">© Textback <span>{commerceEnabled?merchantIdentity.name:"Produktvalidering"}</span></div></footer>}
